replicaCount: 2

image:
  repository: 474668397798.dkr.ecr.us-east-1.amazonaws.com/foodfrenzy
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysql:3306/FoodFrenzy
  - name: SPRING_DATASOURCE_USERNAME
    value: root
  - name: SPRING_DATASOURCE_PASSWORD
    value: root

resources: {}
