apiVersion: v1
kind: Service
metadata:
  name: foodfrenzy
spec:
  type: {{ .Values.service.type }}
  selector:
    app: foodfrenzy
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
